version: "3"

volumes:
  DB-tweetter-postgres:

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - "DB-tweetter-postgres:/var/lib/postgresql/data"
    env_file: .env

  api:
    restart: always
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./src:/usr/src/app/src"
    depends_on:
      - postgres
    links:
      - postgres:postgres
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
